---
- name: Add Port 12345 for front end
  os_security_group_rule:
    security_group: 'group41_http'
    protocol: 'tcp'
    port_range_min: 12345
    port_range_max: 12345
    remote_ip_prefix: 0.0.0.0
    state: present

- name: install python-software-properties
  tags: 'frontend'
  become: yes
  apt:
    name: ['python-software-properties']
    state: latest
    install_recommends: no
    update_cache: yes

- name: set up environment
  tags: 'frontend'
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  args:
    warn: no
  register: setupOutput

- debug:
    msg: "{{ setupOutput }}"

- name: Install node.js and essential
  tags: 'frontend'
  become: yes
  command: "{{ item }}"
  with_items:
    - sudo apt-get install -y nodejs
    - sudo apt-get install -y build-essential

- name: npm i
  tags: 'frontend'
  shell: npm i
  args:
    chdir: /home/ubuntu/TheDeadlySins/FrontEnd
  register: npmIoutput

- debug:
    msg: "{{ npmIoutput }}"

- name: npm run dev
  tags: 'frontend'
  shell: nohup npm run dev 2>&1 &
  async: 10
  poll: 0
  args:
    chdir: /home/ubuntu/TheDeadlySins/FrontEnd
  register: rundev

- debug:
    msg: "{{ rundev }}"