---
- name: set up environment
  tags: 'frontend'
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  args:
    warn: no
  when: ansible_default_ipv4.address == groups['dbserver'][2]
  register: setupOutput

- debug:
    msg: "{{ setupOutput }}"

- name: Install node.js and essential
  tags: 'frontend'
  become: yes
  command: "{{ item }}"
  with_items:
    - sudo apt-get install -y nodejs
    - sudo apt-get install -y build-essential
  args:
    warn: no
  when: ansible_default_ipv4.address == groups['dbserver'][2]

- name: npm i
  tags: 'frontend'
  shell: npm i
  args:
    chdir: /home/ubuntu/TheDeadlySins/FrontEnd
  when: ansible_default_ipv4.address == groups['dbserver'][2]
  register: npmIoutput

- debug:
    msg: "{{ npmIoutput }}"
  when: ansible_default_ipv4.address == groups['dbserver'][2]

- name: npm run dev
  tags: 'frontend'
  shell: nohup npm run dev 2>&1 &
  async: 10
  poll: 0
  args:
    chdir: /home/ubuntu/TheDeadlySins/FrontEnd
  when: ansible_default_ipv4.address == groups['dbserver'][2]
  register: rundev

- debug:
    msg: "{{ rundev }}"
  when: ansible_default_ipv4.address == groups['dbserver'][2]