---
# Create a security group
- name: Create an security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

- name: Create a list of security group names
  set_fact:
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'

- debug:
    msg: "Security group(s) {{ sg_names }} have been created."

# Create security group rules
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  when: item.remote_ip_prefix is defined
  loop: '{{ security_groups }}'

- name: Create internal security groups rule
  os_security_group_rule:
    security_group: internal
    protocol: tcp
    remote_group: internal
    state: present

- name: Create security group rules for port 5984
  os_security_group_rule:
    security_group: 'group41_http'
    protocol: 'tcp'
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    state: present

- name: Create security group rules for port 5986
  os_security_group_rule:
    security_group: 'group41_http'
    protocol: 'tcp'
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
    state: present

- name: Add Port 12345 for front end
  os_security_group_rule:
    security_group: 'group41_http'
    protocol: 'tcp'
    port_range_min: 12345
    port_range_max: 12345
    remote_ip_prefix: 0.0.0.0/0
    state: present