---
- name: Uninstall old versions of docker
  tags: 'docker'
  become: 'yes'
  apt:
    name: ['docker', 'docker-engine', docker-io']
    state: absent

- name: apt-get update
  become: yes
  apt:
    update-cache: yes

- name: Install dependencies
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker apt repository key
  tags: 'docker'
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  tags: 'docker'
  become: 'yes'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.22.0
    state: present

- name: Checking folders
  tags: 'docker'
  become: yes
  stat:
    path: "/etc/systemd/system/docker.service.d"
  register: directory_stats

- name: Create a systemd drop-in directory for the docker service
  tags: 'docker'
  become: yes
  file:
    path: "/etc/systemd/system/docker.service.d"
    recurse: yes
    state: directory
  when: directory_stats.stat.exists == false

- name: Create a file and adds the HTTP_PROXY environment variable
  tags: 'docker'
  become: yes
  copy:
    dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    content: |
        [Service]
        Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000"

- name: Create a file and adds the HTTP_PROXY environment variable
  tags: 'docker'
  become: yes
  copy:
    dest: "/etc/systemd/system/docker.service.d/https-proxy.conf"
    content: |
        [Service]
        Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000"

- name: Flush changes
  tags: 'docker'
  become: yes
  command: systemctl daemon-reload

- name: Restart docker
  tags: 'docker'
  become: yes
  command: systemctl restart docker

- name: Verify thar the configuration has been loaded
  tags: 'docker'
  become: yes
  command: systemctl show --property=Environment docker