- hosts: dbserver
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true

  vars_prompt:
    - name: "githubuser"
      prompt: "Enter your github username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your github password"
      private: yes

  roles:
    # - role: install_common
    # - role: volumes
    # - role: docker
    # - role: couchdb
    - role: harvester
    - role: frontend